abema/go-mp4

- hdlr.go
- hdlr_test.go
- marshaller.go
This PR enables unmarshal of QuickTime-specific HDLR atom.
The handler name is stored as a Pascal string in the QuickTime specs (first byte is the length of the string).
> Implement unmarshaling of the "HandlerName" from HDLR atom in the QuickTime specs

- box.go
- hdlr.go
- hdlr_test.go
- marshaller.go
- meta.go
- meta_test.go
Issue: https://github.com/abema/go-mp4/issues/7
- PString support
- Try to read the data as PString (Length-Prefixed String) for fields having `string=c_p`.
- Check whether the `component_type` of `hdlr` is non-zero.
- `BeforeUnmarshal` function
- Hook a invocation of Unmarshal and override the processing if the box is old QuickTime style.
- Unset `version` and `flags` of `meta`.
> Improve supports for old Quicktime atom

- box_types.go
- box_types_test.go
- extract_test.go
Fix the bug introduced by https://github.com/abema/go-mp4/pull/6 .
Apple style hdlr.name represents empty string by `[]byte{0x00, 0x00}` perhaps.
But I have confirm that from actual MP4 files only, and can found no official technical documentations.
Related to https://github.com/abema/go-mp4/issues/7 , https://github.com/abema/go-mp4/pull/4
> Fix hdlr bug

- box_types.go
- box_types_test.go
- util/string.go
- util/string_test.go
https://github.com/abema/go-mp4/issues/54
Fix the value of bitSize argument from 32 to 64.
> Fix stringify function for fixed point number

- marshaller.go
- marshaller_test.go
@sunfish-shogi
marshaller.writeUvarint(0) is not corresponded to unmarshaller.readUvarint([]byte{0x0});
> Fix marshaller.writeUvarint(0)

- mp4tool/mp4dump/mp4dump.go
Fix not to read payload of co64, sdtp, stss, when the size of these box types is large.
> Speed improvement of mp4tool-dump

- mp4tool/divide/divide.go
- mp4tool/dump/dump.go
- mp4tool/edit/edit.go
- mp4tool/main.go
rename subpackages of mp4tool to remove redundant prefix "mp4".
> rename subpackages of mp4tool

- box_types.go
- box_types_test.go
escape unprintable runes by box_types.go
related to https://github.com/abema/go-mp4/pull/65
> escape unprintable runes by box_types.go

- extract.go
Reject the box type which equals to BoxTypeAny() before matchPath.
> Fix to skip BoxTypeAny() in extract.go

- box_types.go
- marshaller.go
- marshaller_test.go
- read.go
@sunfish-shogi
Related https://github.com/abema/go-mp4/issues/23 Golint
I fixed golint warning **except** `should have comment or be unexported`.
https://goreportcard.com/report/github.com/abema/go-mp4#golint
> Improve golint coverage

- box_types_test.go
- marshaller.go
- marshaller_test.go
@sunfish-shogi
Firefox and Chrome aren't currently able to read varints with a size different than 4. ISO 14496-1 isn't clear on the matter, although it limits the maximum varint size to 4.
This patch forces varints to have a size of 4, allowing a broader compatibility of esds boxes. Sizes greater than 4 are not supported anymore (but this is dictated by the specification).
References:
https://stackoverflow.com/questions/30998150/build-an-esds-box-for-an-mp4-that-firefox-can-play
https://github.com/FFmpeg/FFmpeg/blob/0922c6b01bd50f0ce6e659f765c244f6a8f29eb3/libavformat/movenc.c#L646
ISO 14496-1
PS: thank you very much for this library, it allows [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) to produce and read Low-Latency HLS fragments.
> Improve compatibility of esds boxes

- box_types.go
- box_types_test.go
@sunfish-shogi
This patch adds support for: hvcC, hev1, fiel
The new box types are used by [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) to generate HLS streams with H265 tracks. Everything seems to work correctly with Chrome and Safari (Firefox unfortunately doesn't support H265 yet).
> add H265 box types

- box_types.go
Hello @sunfish-shogi, i thought the H265 implementation was complete but there's a box missing.
According to ISO/IEC FDIS 14496-15:2019(E), section  8.3.2:
> Parameter sets: A parameter set to be used in a picture must be sent prior to the sample containing that picture or in the sample for that picture. For a video stream that a particular sample entry applies to, the video parameter set, sequence parameter sets, and picture parameter sets, shall be stored only in the sample entry when the sample entry name is ‘hvc1’, and may be stored in the sample entry and the samples when the sample entry name is ‘hev1’.
H265 has two sample entry names, the first one is 'hev1' (added in the previous PR) and the second one is 'hvc1'. 'hev1' is used when VPS/SPS/PPS are both in the track header and …
> add hvc1 box

- read.go
https://github.com/abema/go-mp4/issues/132
Fix not to return error when QuickTime atom has padding bytes.
> Fix for QuickTime

- probe.go
@sunfish-shogi
This allows for the correct probing of videos recorded on modern android devices
I'm not sure if this covers all edgecases (especially with videos >4Gi) but this was sufficient for my usecase.
Let me know if you think there is a better approach!
> feat: adapt probe code to allow for co64 box instead of stco

- probe.go
- probe_test.go
This PR is additional changes for #135.
- Revert unnecessary type change of Sample.Size.
- Update test code.
> Additional changes for #135: Update test code and revert type of Sample.Size

- box_types.go
- box_types_test.go
- mp4tool/dump/dump_test.go
Issue: #137 
Fix to display `AudioSampleEntry.SampleRate` with human-readable format.
> Display SampleRate with human-readable format

- box_types_vp.go
- box_types_vp_test.go
@sunfish-shogi
Another day, another codec! these are the boxes used by VP9 and VP8. Tested with Chrome and Firefox.
(i'm discovering that browsers are way more advanced than FFmpeg and Gstreamer regarding codec capabilities).
Standard: https://www.webmproject.org/vp9/mp4
> add VP9 and VP8 boxes

- box_types_iso14496_12.go
- box_types_iso14496_12_test.go
- marshaller.go
This change prevents RAM exhaustion.
- Limit first slice capacity in common marshaller.
- Exclude mdat-box.
- Will not limit for reallocation. (If requested length is larger than real remaining file size, return EOF error.)
- Return an error if name length of hdlr-box is larger than 1024.
#149 
#146
> Prevent RAM exhaustion

- box_info.go
- read_test.go
@sunfish-shogi
When ReadBoxStructure is called against a box with a size of zero, an infinite loop is generated due to the fact that the loop contained in readBoxStructure() never ends. This patch fixes the issue and provides a test case.
> Prevent infinite loop when calling ReadBoxStructure

- marshaller.go
@sunfish-shogi
fi.size is checked 3 times, one time is enough.
> Remove redundant conditions in unmarshalSlice()

- box_types_iso14496_12.go
- box_types_iso14496_12_test.go
- marshaller.go
@sunfish-shogi
While patch #150 is able to prevent RAM exhaustion with the majority of small, specially-crafted strings, it isn'effective against strings that contain mdat boxes. A short string is able to cause RAM exhaustion by setting the mdat box size to a big number.
This PR fixes the issue by replacing size-based checks with checks on the effective size of the underlying buffer, that are performed by using Seek(). In this way, an attacker may cause DoS errors if and only if he is able to upload an amount of data equal to the size of the RAM of the machine, and if there are no size checks before passing the buffer to ReadBoxStructure() or Unmarshal().
Size-based checks are performed only in case of non-uint8 slices, since it's not possible to know in advance the overall size of a …
> Fix out-of-memory errors with mdat boxes and remove size-based checks

- box_types_iso23001_5.go
- box_types_iso23001_5_test.go
@sunfish-shogi
These boxes allows to marshal and unmarshal uncompressed audio tracks.
Tested with VLC and FFmpeg.
> add ISO 23001-5 boxes

- mp4.go
- Add global scope variable `itemBoxFields` to prevent multiple call for `buildFields`.
- Simplify `reflect.TypeOf(payload).Elem()` to `eflect.TypeOf(Item{})`.
related to #159
> Reduce buildFields function call
