ctts.go
elst.go
ftyp.go
pssh.go
stsc.go
stts.go
tfra.go
trun.go

Create named types for inner struct.

named types for inner struct

---

mp4tool/mp4dump/mp4dump.go

Fix mp4tool dump to expand child boxes of large size box

---

free.go
read_test.go
sbgp.go
sgpd.go
smhd.go

- free box
- sbgp box
- sgpd box
- smhd box

Add some box definitions

---

box_types_test.go
marshaller_test.go

Increase test coverage

---

box_types.go
box_types_test.go
mp4tool/mp4divide/mp4divide.go
probe.go

Issue: https://github.com/abema/go-mp4/issues/24

Create test cases for all box types

---

box_types.go
mp4.go

Abolish noVersion const

---

mp4tool/mp4dump/mp4dump.go

Issue: https://github.com/abema/go-mp4/issues/33

Create -full option

---

box_types.go
box_types_test.go

Issue: https://github.com/abema/go-mp4/issues/13

Support sidx and styp

---

box_types.go
box_types_test.go
go.mod
go.sum
mp4.go
mp4_test.go
mp4tool/mp4dump/mp4dump.go
read_test.go

- https://github.com/abema/go-mp4/issues/13
- https://github.com/abema/go-mp4/issues/7

Add box type

---

box.go
box_types.go
box_types_test.go
marshaller.go
string.go

Fix custom fields of sgpd and AVCDecoderConfiguration

Fix custom fields of sgpd and AVCDecoderConfiguration

---

probe.go
probe_test.go

Fix ProbeFra to output CompositionTimeOffset

Fix ProbeFra to output CompositionTimeOffset

---

string.go

Fix for ineffasign

---

box_types.go
box_types_test.go

Create some functions for fixed-point numbers

Create functions for fixed-point

---

mp4tool/mp4dump/mp4dump.go

Handle ErrUnsupportedBoxVersion in mp4tool-dump.

mp4tool dump: handle ErrUnsupportedBoxVersion

---

box_types.go
box_types_test.go
util/io.go
util/io_test.go

https://github.com/abema/go-mp4/issues/47

Support emsg version 1

---

box_types.go
box_types_test.go

https://github.com/abema/go-mp4/issues/50

Fix colr for unknown colour type

---

box_types.go
box_types_test.go

https://github.com/abema/go-mp4/issues/13

Support sdtp box

---

box.go
box_info.go
box_types.go
box_types_test.go
extract.go
marshaller.go
marshaller_test.go
mp4tool/mp4dump/mp4dump.go
mp4tool/mp4edit/mp4edit.go
mp4tool/psshdump/psshdump.go
probe.go
read.go
string.go
string_test.go

Rename BoxStructureStatus to Context.

Rename BoxStructureStatus to Context

---

README.md
box_info.go
box_types.go
box_types_test.go
marshaller.go
mp4.go
mp4_test.go
mp4tool/mp4dump/mp4dump.go
mp4tool/mp4edit/mp4edit.go
read.go
read_test.go

Related to https://github.com/abema/go-mp4/issues/7 https://github.com/abema/go-mp4/issues/13

Support ilst metadata and 3GPP metadata

---

box_types.go
box_types_test.go

Append hidden addribute to Mdhd.Pad.

Append hidden attr to Mdhd.Pad

---

string.go
string_test.go
util/string.go
util/string_test.go

unprintable runes

---

box_types.go
box_types_test.go
go.mod
go.sum

use "-" separator for UUID

---

mp4tool/dump/dump.go

Create hex option of mp4tool-dump

Create hex option of mp4tool-dump

---

string.go

fix error handling

---

box_types.go
box_types_test.go
marshaller.go
read_test.go
string.go
string_test.go

related to https://github.com/abema/go-mp4/issues/13
support following box types
- btrt
- cslg
- frma
- saio
- saiz
- schm
- tenc
- trep

support some box types

---

marshaller.go

Reduce number of times of system call for known size slice.

Enhance performance of unmarshalSlice

---

bitio/read.go

Change argument data type of bitio.NewReader from io.ReadSeeker to io.Reader

Fix argument data type of bitio.NewReader

---

box_types.go
box_types_test.go
extract_test.go
field.go

https://github.com/abema/go-mp4/issues/76

Mark string=c_p tag as deprecated

---

box_types.go
box_types_test.go
mp4tool/divide/divide.go
probe.go

https://github.com/abema/go-mp4/issues/80

make Tkhd struct smart

---

box_types.go
go.mod
mp4tool/dump/dump.go
mp4tool/edit/edit.go
mp4tool/main.go
mp4tool/probe/probe.go
probe.go
probe_test.go

- Create Probe function
- Create mp4tool-probe command (beta)

Probe feature

---

mp4tool/probe/probe.go
probe.go
probe_test.go

Fix detectAACProfile function

---

.circleci/config.yml

- https://about.codecov.io/security-update/
- https://github.com/codecov/codecov-circleci-orb/pull/74

Validate checksum of codecov script

---

mp4tool/dump/dump.go
mp4tool/extract/extract.go
mp4tool/extract/extract_test.go
mp4tool/main.go
mp4tool/util/util.go

Create new command mp4tool-extract.
```
mp4tool extract BOX_TYPE INPUT.mp4
```
```
% mp4tool extract ftyp _examples/sample.mp4 | hexdump -C
00000000  00 00 00 20 66 74 79 70  69 73 6f 6d 00 00 02 00  |... ftypisom....|
00000010  69 73 6f 6d 69 73 6f 32  61 76 63 31 6d 70 34 31  |isomiso2avc1mp41|
00000020
```

add mp4tool-extract command

---

.circleci/config.yml
.github/workflows/test.yml

https://github.com/abema/go-mp4/issues/109

GitHub Actions

---

.github/workflows/test.yml

https://github.com/abema/go-mp4/issues/125

fix GH workflow

---

box_types_opus.go
box_types_opus_test.go

@sunfish-shogi
This boxes allow to support Opus tracks and have been tested with both Chrome and Firefox.
Standard: https://opus-codec.org/docs/opus_in_isobmff.html

add Opus boxes

---

box_types_av1.go
box_types_av1_test.go

@sunfish-shogi
These boxes allow to support AV1 and have been tested with both Chrome and Firefox.
Standard: https://aomediacodec.github.io/av1-isobmff

add AV1 boxes

---

box_types_iso14496_12.go

@sunfish-shogi
This allows to support MPEG-1/2/4 video and M-JPEG tracks.

Add mp4v box

---

cmd/mp4tool/internal/divide/divide.go

Update mp4tool-divide #157

---

.github/workflows/test.yml

update for go 1.22 
https://go.dev/blog/go1.22

Update GH workflow

---

cmd/mp4tool/internal/psshdump/psshdump.go
cmd/mp4tool/internal/psshdump/psshdump_test.go

Fix the bug which psshdump does not show SystemID.

Fix psshdump command

---

box_types_iso14496_30.go
box_types_iso14496_30_test.go

@sunfish-shogi
These boxes allows to marshal and unmarshal WebVTT boxes.
Sample WebVTT in isobmff file is below.
https://github.com/user-attachments/assets/2cc6806b-fa10-448d-af70-67c9f9dcef05

Feat: add ISO 14496-30 WebVTT Box
